adding user personas
HYF-Class21/Sound-Blog-Platform pull request #11
Opened 2023-11-02 09:19 UTC by Mervatabuamro

Adding user personas documentation

2023-11-03 01:08 UTC, jialvaradob approved these changes

2023-11-03 01:31 UTC, jialvaradob commented
Good job! Thanks for linking the issue as well  💯

2023-11-03 01:35 UTC, jialvaradob requested changes
The newly created file is empty, check saving changes on your vscode or maybe paste it directly in github as an edit

2023-11-03 03:45 UTC, Ibrahim86Ali approved these changes

2023-11-03 10:06 UTC, Mervatabuamro commented
OH I did not notice that
now its ready

2023-11-03 13:10 UTC, jialvaradob approved these changes

2023-11-04 19:56 UTC, Neha-2012 commented on planning/user-personas.md
> +- **Bio**: Lexy is a housewife, 35 years old. Most of her day is taking care of kids and house chores. And meeting with neighbors.
Spelling Mistake.

2023-11-04 19:58 UTC, Neha-2012 approved these changes

2023-11-05 02:24 UTC, merged